### ISSUE TITLE
Disconnected stations

### ISSUE THREAD

**Issue by andre-dietrich** [edrys-org/edrys#16]
Hello @edrysorg  I think there is a general problem, that somehow detaches the station. Here are the steps to repeat this bug:

1. Add a module to a classroom, maybe the Markdown-module
2. Open the station
3. Move your User to the station
4. Change some parts within the configuration
5. Reload the station ...

The station sees itself and sometimes also the users, but on the other side, the station does not appear ...

Here is a terminal output:

``` bash
DEBUG Fri Feb 17 2023 12:37:54 GMT+0100 (Central European Standard Time) ["Disconnection","TerminalXXX"]
DEBUG Fri Feb 17 2023 12:37:54 GMT+0100 (Central European Standard Time) ["SSSSSSSSSSSSSSS",{"isTrusted":false}]
DEBUG Fri Feb 17 2023 12:37:54 GMT+0100 (Central European Standard Time) ["SSSSSSSSSSSSSSS",[{"id":"","target":{}}]]
DEBUG Fri Feb 17 2023 12:37:54 GMT+0100 (Central European Standard Time) ["SSSSSSSSSSSSSSS",{"users":{"w@w.de":{"displayName":"Teacher ","room":"Lobby","role":"teacher","dateJoined":1676633862662,"handRaised":false,"connections":[{"id":"","target":{}}]}},"rooms":{"Lobby":{"studentPublicState":"","teacherPublicState":"","teacherPrivateState":""},"Teacher's Lounge":{"studentPublicState":"","teacherPublicState":"","teacherPrivateState":""}}}]
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 40CV-UdYT2esOLLemOYrE undefined {}
[uncaught application error]: Http - connection closed before message completed

    at Object.respondWith (deno:ext/http/01_http.js:317:27)
[uncaught application error]: Http - connection closed before message completed

request: {
  url: "http://localhost:8000/data/readLiveClass/40CV-UdYT2esOLLemOYrE?displayName=TerminalXXX&jwt=eyJhbGciO...",
  method: "GET",
  hasBody: false
}
response: { status: 200, type: undefined, hasBody: true, writable: false }

    at Object.respondWith (deno:ext/http/01_http.js:317:27)
WWWWWWWWWWWWWWWWWWWW 1
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 40CV-UdYT2esOLLemOYrE {
  autoAssign: undefined,
  users: {
    TerminalXXX: {
      displayName: "TerminalXXX",
      room: "Station TerminalXXX",
      role: "teacher",
      dateJoined: 1676633874374,
      handRaised: false,
      connections: [ [Object] ]
    }
  },
  rooms: {
    Lobby: { studentPublicState: "", teacherPublicState: "", teacherPrivateState: "" },
    "Teacher's Lounge": { studentPublicState: "", teacherPublicState: "", teacherPrivateState: "" },
    "Station TerminalXXX": {
      studentPublicState: "",
      teacherPublicState: "",
      teacherPrivateState: "",
      userLinked: "TerminalXXX"
    }
  }
} {
  "40CV-UdYT2esOLLemOYrE": {
    autoAssign: undefined,
    users: {
      TerminalXXX: {
        displayName: "TerminalXXX",
        room: "Station TerminalXXX",
        role: "teacher",
        dateJoined: 1676633874374,
        handRaised: false,
        connections: [Array]
      }
    },
    rooms: {
      Lobby: { studentPublicState: "", teacherPublicState: "", teacherPrivateState: "" },
      "Teacher's Lounge": { studentPublicState: "", teacherPublicState: "", teacherPrivateState: "" },
      "Station TerminalXXX": {
        studentPublicState: "",
        teacherPublicState: "",
        teacherPrivateState: "",
        userLinked: "TerminalXXX"
      }
    }
  }
}
DEBUG Fri Feb 17 2023 12:37:54 GMT+0100 (Central European Standard Time) ["Class Update","40CV-UdYT2esOLLemOYrE",{"users":{"TerminalXXX":{"displayName":"TerminalXXX","room":"Station TerminalXXX","role":"teacher","dateJoined":1676633874374,"handRaised":false,"connections":[{"id":"","target":{}}]}},"rooms":{"Lobby":{"studentPublicState":"","teacherPublicState":"","teacherPrivateState":""},"Teacher's Lounge":{"studentPublicState":"","teacherPublicState":"","teacherPrivateState":""},"Station TerminalXXX":{"studentPublicState":"","teacherPublicState":"","teacherPrivateState":"","userLinked":"TerminalXXX"}}}]
INFO Fri Feb 17 2023 12:37:54 GMT+0100 (Central European Standard Time) 2023-02-17T11:37:54.375Z GET http://localhost:8000/data/readLiveClass/40CV-UdYT2esOLLemOYrE?displayName=TerminalXXX&jwt=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3QHcuZGUiLCJpYXQiOjE2NzY2MjI5MzU0MDMsImV4cCI6MTY3OTIxNDkzNTQwM30.sqHPHIhubJutvcfm6qM9mwfSYyMie8RPJ5ZXtdOuXFVa_vOWA3pr4i3q3rb6u1_Er3uNe4jwNH1Gdw2pwKMTuQ&isStation=true
```

Within the browser I get the following error:

``` bash
The connection to http://localhost:8000/data/readLiveClass/Nxb0Hrr76mz2J75X54-ur?displayName=Teacher+&jwt=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3QHcuZGUiLCJpYXQiOjE2NzY2MjI5MzU0MDMsImV4cCI6MTY3OTIxNDkzNTQwM30.sqHPHIhubJutvcfm6qM9mwfSYyMie8RPJ5ZXtdOuXFVa_vOWA3pr4i3q3rb6u1_Er3uNe4jwNH1Gdw2pwKMTuQ was interrupted while the page was loading.
```

I think one reason is, if a station is opened, it is always associated to a teacher. While reloading, all students and teachers are move back to the lobby. Also the teacher that is associated to the station, even if it is not directly within the room, but only if he opens the station ...

**Comment by andre-dietrich** [comment]
solved
